### ISSUE TITLE
only admin can create raffle?

### ISSUE THREAD

**Issue by best-lucky1030** [zeno3618/raffle-metawin-eth#6]
@zeno3618 
In my case I don't have any sepolia testnet nfts, so can't test.
looks like this.
![image](https://user-images.githubusercontent.com/89365150/236399868-935001f5-308d-4b98-872d-7cb5ebabf424.png)

Could you send the screenshot here how it works?
I mean only admin can create the raffle?

**Comment by zeno3618** [comment]
Yes, Only admin can reate the raffle.

**Comment by best-lucky1030** [comment]
if you don't mind, could you share the screenshot here?
